config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'tasks_edit'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to task_path(task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container mt-5">
  <h1>New Task</h1>

  <%= form_for(@task) do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed, 'Completed' %>
  <%= f.check_box :completed %>
  <%= f.submit %>
  <% end %>

  <%= link_to "Back to Tasks", tasks_path %>
  </div>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1>My Tasks</h1>

  <ul>
    <% @tasks.each_with_index do |task, index| %>
      <li>
        <% if task.completed? %>
          <i class="fa-regular fa-square-check"></i>
        <% else %>
          <i class="fa-regular fa-square"></i>
        <% end %>
        <%= link_to task.title, task_path(task.id), style: "text-decoration: none;" %>
        <%= link_to task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      </li>
    <% end %>
  </ul>

  <%= link_to tasks_new_path do %>
    <i class="fa-solid fa-plus"></i> Add a new task
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <h1>New Task</h1>

  <%= form_for(@task) do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
  <% end %>

  <%= link_to "Back to Tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container mt-5">

  <ul>
    <li>
      <h2><%= @task.title %></h2>
    </li>
    <li>
      <h6><%= @task.details %></h6>
    </li>
    <li>
      <% if @task.completed? %>
        <i class="fa-regular fa-square-check"></i> Task Completed!
      <% else %>
        <i class="fa-regular fa-square"></i> This task is not completed yet!
      <% end %><br>
    </li>
  </ul>

  <%= link_to "Edit Task", tasks_edit_path %>
  <%= link_to "Back to Tasks", tasks_path %>
</div>